### ISSUE TITLE
./automongobackup.sh: line 303: mongodump: command not found

### ISSUE THREAD

**Issue by magiceye** [micahwedemeyer/automongobackup#18]
I download the file and run it by ./automongobackup.sh . I already set mongo's path and mongodump can be use in shell. Why the script says command not found?? I using suse 10, root user, automongobackup.sh has x mod.

**Comment by rubyconvict** [comment]
## mongo installed locally

$ which mongo
/Users/me/mongodb/bin/mongo
$ sudo su
/Users/me/mongodb/bin/mongo
$ exit
### solution:
```
$ sudo ln -s `which mongo` /usr/bin/mongo
$ sudo ln -s `which mongodump` /usr/bin/mongodump
```
also if standalone, change to "no"
$ sudo nano -w ./automongobackup.sh
```
# Use oplog for point-in-time snapshotting.
OPLOG="no"

# Choose other Server if is Replica-Set Master
REPLICAONSLAVE="no"
```
$ sudo bash automongobackup.sh

**Comment by jalogisch** [comment]
Hej @rubyconvict thanks for point this out.

It might really help if you had installed mongo not in a "default" way.

**Comment by ssbarnea** [comment]
At least on Fedora 23+ you need to install `dnf install mongo-tools` because the `mongod` package does not contain these. It would be nice if the tool would attempt to install these if missing.

**Comment by jalogisch** [comment]
hej @ssbarnea please do not highjack this issue.

would you please open a new issue with your feature suggestion.

thank you
