### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by ayoola-solomon** [micahwedemeyer/automongobackup#34]
I am having this error when running the script.
`./automongobackup.sh: line 332: /var/backups/mongodb/127.0.0.1-2102.log: Permission denied`

**Comment by shlomisas** [comment]
did you tried `sudo` it?

**Comment by ayoola-solomon** [comment]
I tried with `sudo`. Still did not work.

**Comment by shlomisas** [comment]
Amm..

1. what is the exact command you're trying to run?
2. can you please provide the out put of `ls -lh ./automongobackup.sh`

**Comment by jalogisch** [comment]
Hej @ayoola-solomon what user did you run the script at?

And who is the owner of /var/backups/mongodb - this looks for me like this user is not able to write to the directory.

Please post the output of `ls -la /var/backups/mongodb` and `id` of the user that runs the script.

thank you

**Comment by jalogisch** [comment]
Unfortunately the issue is not reproducible in the latest release. Please re-open this issue if it still occurs, ideally with a set of reproducible steps. 

Thanks!
