### ISSUE TITLE
Secondary discover fail if authentication is enabled

### ISSUE THREAD

**Issue by contiero-roberto** [micahwedemeyer/automongobackup#36]
Hi.

If you try to backup a replica set with authentication enabled and set primary as DBHOST, when the script executes line
`members=( $(mongo --quiet --host $DBHOST:$DBPORT --eval 'rs.conf().members.forEach(function(x){ print(x.host) })') )`
and line
`is_secondary=$(mongo --quiet --host $member --eval 'rs.isMaster().secondary')`
to discover a secondary, an authorization exception is raised. So, always the primary is chosen for the backup.

I resolved setting a new AUTH variable and putting it as parameter on previous commands. It works for me if, other than backup role, I assign clusterManager role to the user used to execute the dump. Compare the two files inside the zip attached to this issue to see my workaround.
By

Roberto

[automongobackup.zip](https://github.com/micahwedemeyer/automongobackup/files/213866/automongobackup.zip)

**Comment by jalogisch** [comment]
Hej @contiero-roberto it would be really helpful if you send over a pull request with your changes!

thank you!

**Comment by contiero-roberto** [comment]
Hi @jalogisch, sorry for the delayed response. In the meanwhile, the pull request #41 has partially resolved the issue reported by me but I think that also for other replica set members authentication is necessary. So I send over the pull request #42 where I put my change.
Please have a look and let me know what you think.
By

Roberto

**Comment by contiero-roberto** [comment]
@jalogisch, since you closed the pull request #42 yesterday, I think you can close also this issue ;-)
By

Roberto
