### ISSUE TITLE
hourly Backups do not work

### ISSUE THREAD

**Issue by speedone** [micahwedemeyer/automongobackup#44]
I have problems with the hourly Backups. 
I enabled oplog on mongod 3.2 standalone with the --master param on Ubuntu 14.04.
All other rotations are working: daily, week, ... but for hourly backups the script create no file. Also no error message. Any ideas?

DOHOURLY="yes"
HOURLYRETENTION=24

DODAILY="yes"
DAILYRETENTION=0

DOWEEKLY="yes"
WEEKLYDAY=6
WEEKLYRETENTION=4

DOMONTHLY="yes"
MONTHLYRETENTION=4

**Comment by oltoko** [comment]
I have the same problem with a similar configuration. If you take a look at the code at [line 590](https://github.com/micahwedemeyer/automongobackup/blob/master/src/automongobackup.sh#L590), you see that always a daily backup is made.
There is no check if a daily backup already exist!

**Comment by cachedrive** [comment]
Has this been identified as an actual issue? Has it been resolved if so? Last update was Jul 5 2016 reporting the same issue.

**Comment by jalogisch** [comment]
i guess this is fixed with https://github.com/micahwedemeyer/automongobackup/pull/49
